In [2]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

1.3.0


In [13]:
# example usage of tf.tile. 
# Aim: Our tensor a is 3 dimensional in its last dimension.  We call its first dimension the batch dimension.
# For each batch, we want to append a constant vector to all vectors of that batch (go from a to z in output below)
tf.reset_default_graph()

a=tf.constant([[[3,2,1],[7,8,9],[1,1,1]],
               [[0,0,0],[1,1,1],[1,1,1]], 
               [[2,2,2],[3,3,3],[1,1,1]], 
               [[4,4,4],[5,5,5],[1,1,1]]])

# 4 vectors to append, for 4 different batches
y=tf.constant([[-5,-5,-5,-5],[-7,-17,-7,-7],[-9,-9,-9,-39],[-11,-11,-11,-9]])
# make copies of those vectors with tf.tile
h = tf.unstack(y, axis=0)
y1=tf.tile(y,[1,tf.shape(a)[1]])
hh = tf.split(a, 3,axis = -1)

with tf.Session() as sess:
    print("h=")
    print(sess.run(h)) 
    print("hh=")
    print(sess.run(hh))    
    print("a=")
    print(sess.run(a))
    print("a.shape={}".format(a.shape))
    print("y.shape={}".format(y.shape))
    print("y=")
    print(sess.run(y))
    print("y1.shape={}".format(y1.shape))
    print("y1=")
    print(sess.run(y1))

h=
[array([-5, -5, -5, -5], dtype=int32), array([ -7, -17,  -7,  -7], dtype=int32), array([ -9,  -9,  -9, -39], dtype=int32), array([-11, -11, -11,  -9], dtype=int32)]
hh=
[array([[[3],
        [7],
        [1]],

       [[0],
        [1],
        [1]],

       [[2],
        [3],
        [1]],

       [[4],
        [5],
        [1]]], dtype=int32), array([[[2],
        [8],
        [1]],

       [[0],
        [1],
        [1]],

       [[2],
        [3],
        [1]],

       [[4],
        [5],
        [1]]], dtype=int32), array([[[1],
        [9],
        [1]],

       [[0],
        [1],
        [1]],

       [[2],
        [3],
        [1]],

       [[4],
        [5],
        [1]]], dtype=int32)]
a=
[[[3 2 1]
  [7 8 9]
  [1 1 1]]

 [[0 0 0]
  [1 1 1]
  [1 1 1]]

 [[2 2 2]
  [3 3 3]
  [1 1 1]]

 [[4 4 4]
  [5 5 5]
  [1 1 1]]]
a.shape=(4, 3, 3)
y.shape=(4, 4)
y=
[[ -5  -5  -5  -5]
 [ -7 -17  -7  -7]
 [ -9  -9  -9 -39]
 [-11 -11 -11  -9]]
y1.shape=(4, ?)
y1=
[[ -5  -5  -5  -5  -5  -5  -5

In [62]:
sess=tf.Session()
x = tf.placeholder(tf.int32, (3,))
y = x-2
a=tf.constant([[[3,2,1],[7,8,9],[-1,-1,-1]],
               [[0,0,0],[1,1,1],[-2,-2,-2]], 
               [[2,2,2],[3,3,3],[-3,-3,-3]], 
               [[4,4,4],[5,5,5],[-4,-4,-4]],
               [[4,4,4],[5,5,5],[-4,-4,-4]]])
b=tf.constant([[[300,200,100]],
               [[50,40,30]], 
               [[20,20,20]], 
               [[10,10,10]],
               [[90,90,90]]])
xx = tf.tile(x, tf.shape(a)[0:1])

c = tf.concat([a, b], axis=1)


with tf.Session() as session:
    result = session.run(c, feed_dict={x: np.array([20,25,30])})
    print(result)

[[[  3   2   1]
  [  7   8   9]
  [ -1  -1  -1]
  [300 200 100]]

 [[  0   0   0]
  [  1   1   1]
  [ -2  -2  -2]
  [ 50  40  30]]

 [[  2   2   2]
  [  3   3   3]
  [ -3  -3  -3]
  [ 20  20  20]]

 [[  4   4   4]
  [  5   5   5]
  [ -4  -4  -4]
  [ 10  10  10]]

 [[  4   4   4]
  [  5   5   5]
  [ -4  -4  -4]
  [ 90  90  90]]]


In [63]:
sess=tf.Session()
a=tf.constant([[[3,2,1],[7,8,9],[1,1,1]],
               [[0,0,0],[1,1,1],[1,1,1]], 
               [[2,2,2],[3,3,3],[1,1,1]], 
               [[4,4,4],[5,5,5],[1,1,1]]])
y=tf.constant([[-5,-5,-5,-5,-5],[-7,-7,-7,-7,-7],[-9,-9,-9,-9,-9]])
attention = tf.einsum('ijk,kl->ijl', a, y)
print(sess.run(attention))
# print(sess.run(tf.shape(a)[1]))
# y=tf.tile(y,[1,tf.shape(a)[1]])
# print(sess.run(y))
# y=tf.reshape(y,[tf.shape(a)[0],tf.shape(a)[1],-1])
# print(sess.run(y))

[[[ -38  -38  -38  -38  -38]
  [-172 -172 -172 -172 -172]
  [ -21  -21  -21  -21  -21]]

 [[   0    0    0    0    0]
  [ -21  -21  -21  -21  -21]
  [ -21  -21  -21  -21  -21]]

 [[ -42  -42  -42  -42  -42]
  [ -63  -63  -63  -63  -63]
  [ -21  -21  -21  -21  -21]]

 [[ -84  -84  -84  -84  -84]
  [-105 -105 -105 -105 -105]
  [ -21  -21  -21  -21  -21]]]


In [2]:
# example usage of tf.tile. 
# Aim: Our tensor a is 3 dimensional in its last dimension.  We call its first dimension the batch dimension.
# For each batch, we want to append a constant vector to all vectors of that batch (go from a to z in output below)

a=tf.constant([[[3,2,1],[7,8,9],[1,1,1]],
               [[0,0,0],[1,1,1],[1,1,1]], 
               [[2,2,2],[3,3,3],[1,1,1]], 
               [[4,4,4],[5,5,5],[1,1,1]]])

# 4 vectors to append, for 4 different batches
y=tf.constant([[-5,-5,-5,-5],[-7,-7,-7,-7],[-9,-9,-9,-9],[-11,-11,-11,-9]])
# make copies of those vectors with tf.tile
y=tf.tile(y,[1,tf.shape(a)[1]])
# reshape them, so that they can be appended
y=tf.reshape(y,[tf.shape(a)[0],tf.shape(a)[1],-1])
# append
z=tf.concat([a,y],axis=2)

with tf.Session() as sess:
    print("a=")
    print(sess.run(a))
    print("a.shape={}".format(a.shape))
    print("y=")
    print(sess.run(y))
    print("z=")
    print(sess.run(z))

a=
[[[3 2 1]
  [7 8 9]
  [1 1 1]]

 [[0 0 0]
  [1 1 1]
  [1 1 1]]

 [[2 2 2]
  [3 3 3]
  [1 1 1]]

 [[4 4 4]
  [5 5 5]
  [1 1 1]]]
a.shape=(4, 3, 3)
y=
[[[ -5  -5  -5  -5]
  [ -5  -5  -5  -5]
  [ -5  -5  -5  -5]]

 [[ -7  -7  -7  -7]
  [ -7  -7  -7  -7]
  [ -7  -7  -7  -7]]

 [[ -9  -9  -9  -9]
  [ -9  -9  -9  -9]
  [ -9  -9  -9  -9]]

 [[-11 -11 -11  -9]
  [-11 -11 -11  -9]
  [-11 -11 -11  -9]]]
z=
[[[  3   2   1  -5  -5  -5  -5]
  [  7   8   9  -5  -5  -5  -5]
  [  1   1   1  -5  -5  -5  -5]]

 [[  0   0   0  -7  -7  -7  -7]
  [  1   1   1  -7  -7  -7  -7]
  [  1   1   1  -7  -7  -7  -7]]

 [[  2   2   2  -9  -9  -9  -9]
  [  3   3   3  -9  -9  -9  -9]
  [  1   1   1  -9  -9  -9  -9]]

 [[  4   4   4 -11 -11 -11  -9]
  [  5   5   5 -11 -11 -11  -9]
  [  1   1   1 -11 -11 -11  -9]]]


In [8]:
# example usage of a mask tensor
tensor = tf.constant(np.array([[1, 2, 3],[4, 5, 6]]), dtype=tf.float32)
mask = tf.constant(np.array([[True, False, True],[True,True,False]]))

with tf.Session() as sess:
    print("---Tensor")
    print(sess.run(tensor))
    print("---Mask")
    print(sess.run(mask))
    print("---tf.cast(mask,dtype=tf.float32)")
    print(sess.run(tf.cast(mask,dtype=tf.float32)))
    print("---tensor*tf.cast(mask,dtype=tf.float32)")
    print(sess.run(tensor*tf.cast(mask,dtype=tf.float32)))
    print("---tf.boolean_mask(tensor,mask)")
    print(sess.run(tf.boolean_mask(tensor,mask)))

---Tensor
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
---Mask
[[ True False  True]
 [ True  True False]]
---tf.cast(mask,dtype=tf.float32)
[[ 1.  0.  1.]
 [ 1.  1.  0.]]
---tensor*tf.cast(mask,dtype=tf.float32)
[[ 1.  0.  3.]
 [ 4.  5.  0.]]
---tf.boolean_mask(tensor,mask)
[ 1.  3.  4.  5.]


In [3]:
# Using our knowledge about tf tile to append a sentinel vector (go from a to z in output below)
a=tf.constant([[[1,0,0,0],[2,0,0,0],[3,0,0,0]],[[-1,0,0,0],[-2,0,0,0],[-3,0,0,0]]])
b=tf.constant([7,7,7,7])
b=tf.tile(b,tf.shape(a)[0:1])
b=tf.reshape(b,(-1,1,tf.shape(a)[2]))
z=tf.concat([a,b],axis=1)
print("a={}".format(a))
print("b={}".format(b))

with tf.Session() as sess:
    print("a")
    print(sess.run(a))
    print("b")
    print(sess.run(b))
    print("z")
    print(sess.run(z))

a=Tensor("Const:0", shape=(2, 3, 4), dtype=int32)
b=Tensor("Reshape:0", shape=(?, 1, ?), dtype=int32)
a
[[[ 1  0  0  0]
  [ 2  0  0  0]
  [ 3  0  0  0]]

 [[-1  0  0  0]
  [-2  0  0  0]
  [-3  0  0  0]]]
b
[[[7 7 7 7]]

 [[7 7 7 7]]]
z
[[[ 1  0  0  0]
  [ 2  0  0  0]
  [ 3  0  0  0]
  [ 7  7  7  7]]

 [[-1  0  0  0]
  [-2  0  0  0]
  [-3  0  0  0]
  [ 7  7  7  7]]]


In [17]:
W1=tf.constant([[[1,1,1,1],[2,2,2,2],[3,3,3,3]],[[1,0,0,0],[-2,0,0,0],[-3,0,0,0]]])
ut_r=tf.constant([[7,7],[8,8],[3,3],[5,5],[1,1],[9,9] ])
print(W1)
print(ut_r)
mt1 = tf.einsum('bt,top->bop', ut_r, W1)
with tf.Session() as sess:
    print("mt1")
    print(sess.run(mt1))

Tensor("Const_26:0", shape=(2, 3, 4), dtype=int32)
Tensor("Const_27:0", shape=(6, 2), dtype=int32)
mt1
[[[14  7  7  7]
  [ 0 14 14 14]
  [ 0 21 21 21]]

 [[16  8  8  8]
  [ 0 16 16 16]
  [ 0 24 24 24]]

 [[ 6  3  3  3]
  [ 0  6  6  6]
  [ 0  9  9  9]]

 [[10  5  5  5]
  [ 0 10 10 10]
  [ 0 15 15 15]]

 [[ 2  1  1  1]
  [ 0  2  2  2]
  [ 0  3  3  3]]

 [[18  9  9  9]
  [ 0 18 18 18]
  [ 0 27 27 27]]]


In [11]:
#Another example needed for sentinel implementation
a=tf.constant([[1,1,0,0],[1,0,0,0]],dtype=tf.float32)
b=tf.constant([0],dtype=tf.float32)
b=tf.tile(b,[tf.shape(a)[0]])
print(b.shape)
print(a.shape)
b=tf.reshape(b,(tf.shape(a)[0],1))
z=tf.concat([a,b],axis=1)
with tf.Session() as sess:
    print("z")
    print(sess.run(z))


(?,)
(2, 4)
z
[[ 1.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]]


In [5]:
# In the code of the DCN_model, adding a sentinel could look like this (not yet implemented)
#logging.info("q_outputs={}".format(q_outputs))
#q_sentinel = tf.get_variable("q_sentinel", (rnn_size,), initializer=tf.contrib.layers.xavier_initializer())
#q_sentinel = tf.tile(q_sentinel, tf.shape(q_outputs)[0:1])
#q_sentinel = tf.reshape(q_sentinel, (-1, 1, tf.shape(q_outputs)[2]))
#Qprime = tf.concat([q_outputs, q_sentinel], axis=1)

In [20]:
# example usage of softmax
a=tf.constant([[[1,0,2,0],[2,0,3,0],[3,0,4,0]],[[5,0,6,0],[6,0,7,0],[7,0,8,0]]],dtype='float32')

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(tf.nn.softmax(a)))
    print(sess.run(tf.nn.softmax(tf.transpose(a,[0,2,1]))))
#=>softmax is row wise

[[[ 1.  0.  2.  0.]
  [ 2.  0.  3.  0.]
  [ 3.  0.  4.  0.]]

 [[ 5.  0.  6.  0.]
  [ 6.  0.  7.  0.]
  [ 7.  0.  8.  0.]]]
[[[  2.24515244e-01   8.25945437e-02   6.10295713e-01   8.25945437e-02]
  [  2.50692427e-01   3.39275263e-02   6.81452632e-01   3.39275263e-02]
  [  2.61927158e-01   1.30405845e-02   7.11991787e-01   1.30405845e-02]]

 [[  2.67970264e-01   1.80556939e-03   7.28418648e-01   1.80556939e-03]
  [  2.68583328e-01   6.65751519e-04   7.30085194e-01   6.65751519e-04]
  [  2.68809587e-01   2.45122617e-04   7.30700195e-01   2.45122617e-04]]]
[[[ 0.09003057  0.24472848  0.66524094]
  [ 0.33333334  0.33333334  0.33333334]
  [ 0.09003057  0.24472848  0.66524094]
  [ 0.33333334  0.33333334  0.33333334]]

 [[ 0.09003057  0.24472848  0.66524094]
  [ 0.33333334  0.33333334  0.33333334]
  [ 0.09003057  0.24472848  0.66524094]
  [ 0.33333334  0.33333334  0.33333334]]]


In [7]:
# gather_nd example
logits = tf.constant([[[10.0, 10.0, 20.0, 20.0],
                      [11.0, 10.0, 10.0, 30.0],
                      [12.0, 10.0, 10.0, 20.0],
                      [13.0, 10.0, 10.0, 20.0]],
                     [[14.0, 11.0, 21.0, 31.0],
                      [15.0, 11.0, 11.0, 21.0],
                      [16.0, 11.0, 11.0, 21.0],
                      [17.0, 11.0, 11.0, 21.0]]])

# pick vector 1 in batch 0, then vec 3 in batch 1 then vec 1 in batch 1
indices = tf.constant([[0,1],[1,3],[1,1]]) 

result = tf.gather_nd(logits, indices)
with tf.Session() as sess:
    print("------------logits")
    print(sess.run(logits))
    print("------------result")
    print(sess.run(result))


------------logits
[[[ 10.  10.  20.  20.]
  [ 11.  10.  10.  30.]
  [ 12.  10.  10.  20.]
  [ 13.  10.  10.  20.]]

 [[ 14.  11.  21.  31.]
  [ 15.  11.  11.  21.]
  [ 16.  11.  11.  21.]
  [ 17.  11.  11.  21.]]]
------------result
[[ 11.  10.  10.  30.]
 [ 17.  11.  11.  21.]
 [ 15.  11.  11.  21.]]


In [7]:
#tf range is simple :)

pick = tf.constant([0,3,2],dtype='int32') 
print(pick)
print(tf.shape(pick))
idx = tf.range(0,tf.shape(pick)[0],1)

with tf.Session() as sess:
    print(sess.run(tf.range(0,2,1))) #start, stop, step
    print(sess.run(tf.range(-1,7,3)))
    print(sess.run(idx))

Tensor("Const_7:0", shape=(3,), dtype=int32)
Tensor("Shape_6:0", shape=(1,), dtype=int32)
[0 1]
[-1  2  5]
[0 1 2]


In [9]:
# Example code for picking us and ue from U using tf.gather_nd() (see DCN_model.py)
logits = tf.constant([[[10.0, 10.0, 20.0, 20.0],
                      [11.0, 10.0, 10.0, 30.0],
                      [12.0, 10.0, 10.0, 20.0],
                      [13.0, 10.0, 10.0, 20.0]],
                     [[14.0, 11.0, 21.0, 31.0],
                      [15.0, 11.0, 11.0, 21.0],
                      [16.0, 11.0, 11.0, 21.0],
                      [17.0, 11.0, 11.0, 21.0]],
                     [[-1, 11.0, 21.0, 31.0],
                      [-2, 11.0, 11.0, 21.0],
                      [-3, 11.0, 11.0, 21.0],
                      [-4, 11.0, 11.0, 21.0]]])

# in theses 3 batches of logits, I want to pick vec 0 in batch 0, vec 3 in batch 1, vec 2 in batch 2
pick = tf.constant([0,3,2],dtype='int32') 
print(pick)
idx = tf.range(0,tf.shape(pick)[0],1)
n_idx = tf.stack([idx,pick],axis=1)

print(logits)

result = tf.gather_nd(logits, n_idx)

with tf.Session() as sess:
    print(10*"-"+"logits")
    print(sess.run(logits))
    print(10*"-"+"concat idx and pick")
    print(sess.run(tf.concat([idx,pick],axis=0)))
    print(10*"-"+"stack idx and pick to obtain n_idx")
    print(sess.run(n_idx))
    print(10*"-"+"access logits via the index array n_idx")
    print(sess.run(result))

Tensor("Const_10:0", shape=(3,), dtype=int32)
Tensor("Const_9:0", shape=(3, 4, 4), dtype=float32)
----------logits
[[[ 10.  10.  20.  20.]
  [ 11.  10.  10.  30.]
  [ 12.  10.  10.  20.]
  [ 13.  10.  10.  20.]]

 [[ 14.  11.  21.  31.]
  [ 15.  11.  11.  21.]
  [ 16.  11.  11.  21.]
  [ 17.  11.  11.  21.]]

 [[ -1.  11.  21.  31.]
  [ -2.  11.  11.  21.]
  [ -3.  11.  11.  21.]
  [ -4.  11.  11.  21.]]]
----------concat idx and pick
[0 1 2 0 3 2]
----------stack idx and pick to obtain n_idx
[[0 0]
 [1 3]
 [2 2]]
----------access logits via the index array n_idx
[[ 10.  10.  20.  20.]
 [ 17.  11.  11.  21.]
 [ -3.  11.  11.  21.]]


In [48]:
tf.reset_default_graph()
# map_fn example. Pretty near to what is needed for the HMN decoder
# Aim in this example: Each vector in U (along last dimension), should be mapped to its dot product with [2,0,1,0]
# but assume that we have to transpose U first and have to work with U_transpose=tf.transpose(U,[1,0,2])
U=tf.constant([[[1,4,3,0],[2,0,-1,0],[7,0,5,0]],[[-1,0,0,0],[-2,0,0,0],[-3,5,5,5]]], dtype='float32')
U_transpose=tf.transpose(U,[1,0,2])
print(U)
print(U_transpose)
proj = tf.constant([2,0,1,0],dtype='float32')
def funci(u_t,projo):
    print("here",u_t)
    return tf.reduce_sum(tf.multiply(u_t, projo),axis=1)
#fn = lambda u_t: tf.multiply(u_t, proj)
Utilde=tf.map_fn(lambda u_t: funci(u_t,proj), U_transpose, dtype=tf.float32)
print(Utilde.shape)
alpha = tf.transpose(Utilde,[1,0])
with tf.Session() as sess:
    print(10*"-"+"U")
    print(sess.run(U))
    print(10*"-"+"U_transpose")
    print(sess.run(U_transpose))
    print(10*"-"+"Utilde")
    print(sess.run(Utilde))
    print("-"*10+"tf.reshape(Utilde,[2,3])) fails to do the right thing!")
    print(sess.run(tf.reshape(Utilde,[2,3])))
    print("-"*10+"tf.transpose(Utilde,[1,0])) gives the desired result")
    print(sess.run(tf.transpose(Utilde,[1,0])))
    print("-"*10)
    print(sess.run(tf.argmax(alpha,1)))

Tensor("Const:0", shape=(2, 3, 4), dtype=float32)
Tensor("transpose:0", shape=(3, 2, 4), dtype=float32)
('here', <tf.Tensor 'map/while/TensorArrayReadV3:0' shape=(2, 4) dtype=float32>)
(3, 2)
----------U
[[[ 1.  4.  3.  0.]
  [ 2.  0. -1.  0.]
  [ 7.  0.  5.  0.]]

 [[-1.  0.  0.  0.]
  [-2.  0.  0.  0.]
  [-3.  5.  5.  5.]]]
----------U_transpose
[[[ 1.  4.  3.  0.]
  [-1.  0.  0.  0.]]

 [[ 2.  0. -1.  0.]
  [-2.  0.  0.  0.]]

 [[ 7.  0.  5.  0.]
  [-3.  5.  5.  5.]]]
----------Utilde
[[  5.  -2.]
 [  3.  -4.]
 [ 19.  -1.]]
----------tf.reshape(Utilde,[2,3])) fails to do the right thing!
[[  5.  -2.   3.]
 [ -4.  19.  -1.]]
----------tf.transpose(Utilde,[1,0])) gives the desired result
[[  5.   3.  19.]
 [ -2.  -4.  -1.]]
----------
[2 2]


In [35]:
# example usage of reduce_max, necessary for the HMN decoder
U=tf.constant([[1,2,3],[7,8,9], [17,8,9]])
with tf.Session() as sess:
    print(sess.run(U))
    x = tf.reduce_mean(U)
    print(sess.run(x))
    x_resh = tf.reshape(x, [-1])
#     print(sess.run(x_resh))
# #     print(sess.run(tf.argmax(U,axis=1)))
# #     print(sess.run(tf.reduce_mean(U,axis=1)))

[[ 1  2  3]
 [ 7  8  9]
 [17  8  9]]
7


In [28]:
alpha=tf.constant([[1,12,3],[17,8,9]])
alphaa=tf.constant([1,2,3])
beta=tf.constant([[8,4,6],[2,2,3]])
alphaP=alphaa+1
with tf.Session() as sess:
#     print(sess.run([alpha, beta]))
    print(sess.run(tf.argmax(alpha,axis=-1)))
#     print(sess.run(tf.reduce_sum([alpha, beta])))
#     print(sess.run((alphaP)))
    

[1 0]


In [16]:
mask=tf.sequence_mask([1, 3, 2], 5)
print(mask)
mask_1=tf.expand_dims(mask, 2)
score_mask = tf.tile(mask_1, (1, 1, 5))
print(mask_1)
with tf.Session() as sess:
    print(sess.run(mask))
    print(sess.run(mask_1))
    print(sess.run(score_mask))

Tensor("SequenceMask_9/Less:0", shape=(3, 5), dtype=bool)
Tensor("ExpandDims_8:0", shape=(3, 5, 1), dtype=bool)
[[ True False False False False]
 [ True  True  True False False]
 [ True  True False False False]]
[[[ True]
  [False]
  [False]
  [False]
  [False]]

 [[ True]
  [ True]
  [ True]
  [False]
  [False]]

 [[ True]
  [ True]
  [False]
  [False]
  [False]]]
[[[ True  True  True  True  True]
  [False False False False False]
  [False False False False False]
  [False False False False False]
  [False False False False False]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [False False False False False]
  [False False False False False]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [False False False False False]
  [False False False False False]
  [False False False False False]]]


In [28]:
d=tf.constant([[[3,2,1,4],[7,8,9,2],[1,1,1,3]],
               [[0,0,0,5],[1,1,1,8],[1,1,1,9]]])
print(d)
q=tf.constant([[[1,1,2,1,3],[2,2,1,2,7],[0,0,0,1,2]],
               [[0,0,0,5,8],[1,1,1,8,6],[1,1,1,9,4]]])
print(q)

unmasked_affinity = tf.einsum('ndh,ndq->nqh', d, q)

with tf.Session() as sess:
    print("ddddd")
    print(sess.run(d))
    print("qqqqqq")
    print(sess.run(q))
    print("afffff ")
    print(sess.run(unmasked_affinity))

Tensor("Const_26:0", shape=(2, 3, 4), dtype=int32)
Tensor("Const_27:0", shape=(2, 3, 5), dtype=int32)
ddddd
[[[3 2 1 4]
  [7 8 9 2]
  [1 1 1 3]]

 [[0 0 0 5]
  [1 1 1 8]
  [1 1 1 9]]]
qqqqqq
[[[1 1 2 1 3]
  [2 2 1 2 7]
  [0 0 0 1 2]]

 [[0 0 0 5 8]
  [1 1 1 8 6]
  [1 1 1 9 4]]]
afffff 
[[[ 17  18  19   8]
  [ 17  18  19   8]
  [ 13  12  11  10]
  [ 18  19  20  11]
  [ 60  64  68  32]]

 [[  2   2   2  17]
  [  2   2   2  17]
  [  2   2   2  17]
  [ 17  17  17 170]
  [ 10  10  10 124]]]


In [17]:
proj = tf.constant([20,25,30,10,4])
print(proj)
document_length0 = tf.placeholder(tf.int32, (None,), name='document_length0')
print(document_length0)
start = tf.zeros((5,), dtype=tf.int32)
print(start)
end = proj - 1
answer = tf.stack([start, end], axis=1)
print(answer)
not_settled = tf.tile([True], (8,))
ta = tf.TensorArray(dtype=tf.int32, size=3)
print(ta)

with tf.Session() as session:
    print(session.run(start))
    print(session.run(end))
    print(session.run(answer))
    print(session.run(not_settled))

Tensor("Const_7:0", shape=(5,), dtype=int32)
Tensor("document_length0_3:0", shape=(?,), dtype=int32)
Tensor("zeros_13:0", shape=(5,), dtype=int32)
Tensor("stack_10:0", shape=(5, 2), dtype=int32)
[0 0 0 0 0]
[19 24 29  9  3]
[[ 0 19]
 [ 0 24]
 [ 0 29]
 [ 0  9]
 [ 0  3]]
[ True  True  True  True  True  True  True  True]


In [19]:
import numpy as np
import tensorflow as tf    

# 1000 sequence in the length of 100
matrix = tf.placeholder(tf.int32, shape=(10, 10), name="input_matrix")
matrix_rows = tf.shape(matrix)[0]
ta = tf.TensorArray(dtype=tf.int32, size=matrix_rows)

init_state = (0, ta)
condition = lambda i, _: i < matrix_rows
body = lambda i, ta: (i + 1, ta.write(i, matrix[i] * 2))
n, ta_final = tf.while_loop(condition, body, init_state)
# get the final result
ta_final_result = ta_final.stack()

# run the graph
with tf.Session() as sess:
    # print the output of ta_final_result
    print sess.run(ta_final_result, feed_dict={matrix: np.ones(shape=(10,10), dtype=np.int32)})

[[2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]]


In [25]:
tf.reset_default_graph()
import numpy as np

n_steps = 2
n_inputs = 3
n_neurons = 5

X = tf.placeholder(dtype=tf.float32, shape=[None, n_steps, n_inputs])
seq_length = tf.placeholder(tf.int32, [None])

basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, sequence_length=seq_length, dtype=tf.float32)

X_batch = np.array([
  # t = 0      t = 1
  [[0, 1, 2], [9, 8, 7]], # instance 0
  [[3, 4, 5], [0, 0, 0]], # instance 1
])
seq_length_batch = np.array([2, 1])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    outputs_val, states_val = sess.run([outputs, states], 
                                     feed_dict={X: X_batch, seq_length: seq_length_batch})
    print('outputs:')
    print(sess.run(tf.shape(outputs_val)))
    print(outputs_val)
    print('\nstates:')
    print(states_val)

outputs:
[2 2 5]
[[[ 0.10392351 -0.40379575  0.33943516 -0.2635788   0.68510091]
  [-0.99821121 -0.99999875 -0.92825377 -0.99843013  0.99999982]]

 [[-0.74601275 -0.99539089 -0.09117992 -0.9357574   0.99940032]
  [ 0.          0.          0.          0.          0.        ]]]

states:
[[-0.99821121 -0.99999875 -0.92825377 -0.99843013  0.99999982]
 [-0.74601275 -0.99539089 -0.09117992 -0.9357574   0.99940032]]


In [36]:
tf.reset_default_graph()
state_size=6
lstm_dec = tf.contrib.rnn.LSTMCell(num_units=state_size)
state = lstm_dec.zero_state(2, dtype=tf.float32)
encoding = tf.placeholder(dtype=tf.float32, shape=[None, 6])
output, state = lstm_dec(encoding, state)
X_batch = np.array(
  [[0, 1, 2, 9, 8, 7], 
  [3, 4, 5,0, 1, 3]])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    outputs_val, states_val = sess.run([output, state], 
                                     feed_dict={encoding: X_batch})
    print('outputs:')
    print(sess.run(tf.shape(outputs_val)))
    print(outputs_val)
    print('\nstates:')
#     print(sess.run(tf.shape(states_val)))
    print(states_val)


outputs:
[2 6]
[[-0.00059593  0.00258833 -0.21033162 -0.00067049 -0.14312631 -0.31653395]
 [ 0.29717636  0.10479536 -0.04902191  0.02340557  0.0264852   0.41031399]]

states:
LSTMStateTuple(c=array([[ -8.47961660e-03,   4.81678136e-02,  -7.84035921e-01,
         -6.87910477e-04,  -5.49614251e-01,  -9.96938109e-01],
       [  4.05349284e-01,   1.13499925e-01,  -4.16956961e-01,
          4.35479954e-02,   6.23860434e-02,   4.93930310e-01]], dtype=float32), h=array([[-0.00059593,  0.00258833, -0.21033162, -0.00067049, -0.14312631,
        -0.31653395],
       [ 0.29717636,  0.10479536, -0.04902191,  0.02340557,  0.0264852 ,
         0.41031399]], dtype=float32))


In [44]:
tf.reset_default_graph()
proj = tf.constant([[20,25,30,10,4],[1,2,3,4,5]])
print(proj)
proj_2 = tf.expand_dims(proj, 1)
print(proj_2)
maxlen=8
proj_3 = tf.tile(proj_2, (1, maxlen, 1))

with tf.Session() as sess:
    print("proj")
    print(sess.run(proj))
    print("proj_2")
    print(sess.run(proj_2))
    print("proj_3")
    print(sess.run(proj_3))

Tensor("Const:0", shape=(2, 5), dtype=int32)
Tensor("ExpandDims:0", shape=(2, 1, 5), dtype=int32)
proj
[[20 25 30 10  4]
 [ 1  2  3  4  5]]
proj_2
[[[20 25 30 10  4]]

 [[ 1  2  3  4  5]]]
proj_3
[[[20 25 30 10  4]
  [20 25 30 10  4]
  [20 25 30 10  4]
  [20 25 30 10  4]
  [20 25 30 10  4]
  [20 25 30 10  4]
  [20 25 30 10  4]
  [20 25 30 10  4]]

 [[ 1  2  3  4  5]
  [ 1  2  3  4  5]
  [ 1  2  3  4  5]
  [ 1  2  3  4  5]
  [ 1  2  3  4  5]
  [ 1  2  3  4  5]
  [ 1  2  3  4  5]
  [ 1  2  3  4  5]]]


In [50]:
tf.reset_default_graph()
x = tf.constant(5.0, shape=[5, 6])
w = tf.constant([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])
xw = tf.multiply(x, w)
max_in_rows = tf.reduce_max(xw, 1)
print(x)
print(w)
sess = tf.Session()
print sess.run(x)
print sess.run(w)
print sess.run(xw)
print sess.run(max_in_rows)
# ==> [25.0, 25.0, 25.0, 25.0, 25.0]

Tensor("Const:0", shape=(5, 6), dtype=float32)
Tensor("Const_1:0", shape=(6,), dtype=float32)
[[ 5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.]]
[ 0.  1.  2.  3.  4.  5.]
[[  0.   5.  10.  15.  20.  25.]
 [  0.   5.  10.  15.  20.  25.]
 [  0.   5.  10.  15.  20.  25.]
 [  0.   5.  10.  15.  20.  25.]
 [  0.   5.  10.  15.  20.  25.]]
[ 25.  25.  25.  25.  25.]


In [57]:
tf.reset_default_graph()
proj_1 = tf.constant([[20,25,30,10,4],[1,2,3,4,5]])
proj_2 = tf.constant([[10,5,13,11,49],[10,4,8,7,6]])
logit = tf.stack([proj_1, proj_2], axis=2)
start_logit, end_logit = logit[:, :, 0], logit[:, :, 1]
with tf.Session() as sess:
    print(sess.run(proj_1))
    print(sess.run(proj_2))
    print(sess.run(logit))
    print(sess.run(start_logit))
    print(sess.run(end_logit))

[[20 25 30 10  4]
 [ 1  2  3  4  5]]
[[10  5 13 11 49]
 [10  4  8  7  6]]
[[[20 10]
  [25  5]
  [30 13]
  [10 11]
  [ 4 49]]

 [[ 1 10]
  [ 2  4]
  [ 3  8]
  [ 4  7]
  [ 5  6]]]
[[20 25 30 10  4]
 [ 1  2  3  4  5]]
[[10  5 13 11 49]
 [10  4  8  7  6]]


In [62]:
tf.reset_default_graph()
batch_size=10
not_settled = tf.tile([True], (batch_size,))
print(not_settled)
x = tf.reduce_any(not_settled)
with tf.Session() as sess:
    print(sess.run(not_settled))
    print(sess.run(x))

Tensor("Tile:0", shape=(10,), dtype=bool)
[ True  True  True  True  True  True  True  True  True  True]
True


In [66]:
tf.reset_default_graph()
encoding=tf.constant([[[3,2,1,4],[7,8,9,2],[1,1,1,3]],
               [[0,0,0,5],[1,1,1,8],[1,1,1,9]]])
batch_size=2
not_settled = tf.constant([False,True])
enc_masked = tf.boolean_mask(encoding, not_settled)
with tf.Session() as sess:
    print(sess.run(encoding))
    print(sess.run(not_settled))
    print(sess.run(enc_masked))

[[[3 2 1 4]
  [7 8 9 2]
  [1 1 1 3]]

 [[0 0 0 5]
  [1 1 1 8]
  [1 1 1 9]]]
[False  True]
[[[0 0 0 5]
  [1 1 1 8]
  [1 1 1 9]]]


In [81]:
tf.reset_default_graph()
answer=tf.constant([[1,2],[3,4],[7,8]])
new_answer=tf.constant([[1,2],[5,4],[2,8]])
not_settled = tf.reduce_any(tf.not_equal(answer, new_answer), axis=1)
batch_size=3
new_idx = tf.boolean_mask(tf.range(batch_size), not_settled)
with tf.Session() as sess:
    print(sess.run(answer))
    print(sess.run(new_answer))
    print(sess.run(tf.not_equal(answer, new_answer)))
    print(sess.run(not_settled))
    print(sess.run(new_idx))
    print(sess.run([tf.range(batch_size), new_idx]))

[[1 2]
 [3 4]
 [7 8]]
[[1 2]
 [5 4]
 [2 8]]
[[False False]
 [ True False]
 [ True False]]
[False  True  True]
[1 2]
[array([0, 1, 2], dtype=int32), array([1, 2], dtype=int32)]


In [76]:
tf.reset_default_graph()
x=tf.constant([0.1, -1., 5.2, 4.3, -1., 7.4])
condition_mask=tf.not_equal(x,tf.constant(-1.))
partitioned_data = tf.dynamic_partition(
    x, tf.cast(condition_mask, tf.int32) , 2)
partitioned_data[1] = partitioned_data[1] + 1.0

condition_indices = tf.dynamic_partition(
    tf.range(tf.shape(x)[0]), tf.cast(condition_mask, tf.int32) , 2)

xx = tf.dynamic_stitch(condition_indices, partitioned_data)

with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(condition_mask))
    print(sess.run(tf.cast(condition_mask, tf.int32)))
    print("partitioned_data", sess.run(partitioned_data))
    print("condition_indices", sess.run(condition_indices))
    print(sess.run(xx))

[ 0.1        -1.          5.19999981  4.30000019 -1.          7.4000001 ]
[ True False  True  True False  True]
[1 0 1 1 0 1]
('partitioned_data', [array([-1., -1.], dtype=float32), array([ 1.10000002,  6.19999981,  5.30000019,  8.39999962], dtype=float32)])
('condition_indices', [array([1, 4], dtype=int32), array([0, 2, 3, 5], dtype=int32)])
[ 1.10000002 -1.          6.19999981  5.30000019 -1.          8.39999962]


In [89]:
tf.reset_default_graph()
logits = tf.TensorArray(dtype=tf.int32, size=3)
logit_0 = tf.constant([[20,25,30,10,4],[1,2,3,4,5]])
logit_1 = tf.constant([[10,5,13,11,49],[10,4,8,7,6]])
logit_2 = tf.constant([[10,15,23,14,79],[19,22,54,71,6]])
logits = logits.write(0, logit_0)
logits = logits.write(1, logit_1)
logits = logits.write(2, logit_2)
logitss = logits.concat()
print(logits)
with tf.Session() as sess:
    print(sess.run(logitss))

[[20 25 30 10  4]
 [ 1  2  3  4  5]
 [10  5 13 11 49]
 [10  4  8  7  6]
 [10 15 23 14 79]
 [19 22 54 71  6]]


In [110]:
tf.reset_default_graph()
y = tf.constant([[20,25],[30,10],[1,2],[3,4],[11,12],[33,4]])
max_iter=3
x=y[:, 0]
x_sp = tf.split(x, max_iter)
x_st = tf.stack(x_sp,axis=1)

z=y[:, 1]
z_sp = tf.split(z, max_iter)
z_st = tf.stack(z_sp,axis=1)

loss_per_example = tf.reduce_mean(x_st + z_st, axis=1)
with tf.Session() as sess:
#     print(sess.run(tf.shape(x)))
#     print(sess.run((x)))
#     print(sess.run((x_sp)))
    print(sess.run((x_st)))
    print(sess.run((z_st)))
    print(sess.run(loss_per_example))

[[20  1 11]
 [30  3 33]]
[[25  2 12]
 [10  4  4]]
[23 28]


In [113]:
(20+1+11+25+2+12)/3

23

In [114]:
def join(first, second):
    a = []
    for i, j in zip(first, second):
        a.append(i+j)
    return tuple(a)

In [115]:
first=[[2,3,5],[1,2,4]]
second = [[12,23,8],[4,1,9]]
joined = join(first, second)
print(joined)

([2, 3, 5, 12, 23, 8], [1, 2, 4, 4, 1, 9])


In [116]:
[2,3,5]+[12,23,8]

[2, 3, 5, 12, 23, 8]

In [123]:
first=np.array([[1,2],[3,4],[7,8]])
second=np.array([[1,2],[5,4],[2,8]])
# start=[]
# start.append(first)
# start.append(second)
# print start
# print np.concatenate(start)

In [121]:
def exact_match(prediction, truth):
    total = 0
    em_total = 0
    for i, single_truth in enumerate(truth):
        if [prediction[0][i], prediction[1][i]] == single_truth:  # can possibly remove loop and just do the full comparison
            em_total +=1
        total += 1
    em_total /= total
    return em_total

In [124]:
exact_match(first,second)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [130]:
name="mehdi"
score=2
i=3
print('not_settled_iter_{%d}' %(i+1))

not_settled_iter_{4}


In [139]:
import logging
logging.basicConfig(level=logging.INFO)
num_parameters=2
num_elementss=10
v='s'
logging.info('Number of parameters %d' % num_parameters)
logging.info('Variable {v} has {num} entries'.format(v=v, num=num_elementss))

In [144]:
i=8
"flags_{}.json".format(i)

'flags_8.json'

In [147]:
from collections import Counter
prediction_range=range(5,10)
true_range=range(3,7)
print(prediction_range)
print(true_range)
common = Counter(prediction_range) & Counter(true_range)
print(common)

[5, 6, 7, 8, 9]
[3, 4, 5, 6]
Counter({5: 1, 6: 1})


In [153]:
step=2
dev_loss=60
train_f1=12
dev_f1=34
train_em=22
dev_em=88
print('Step %d' %step, 'Dev loss %f' %dev_loss, 'Train/Dev F1: %f %f' %(train_f1,dev_f1), 'Train/Dev EM: %f %f' %(train_em,dev_em))
# print('Step %d' %step, 'Dev loss %f' %dev_loss, 'Train/Dev F1: %f %f' %train_f1 %dev_f1, 'Train/Dev EM: %f %f' %train_em %dev_em) 

('Step 2', 'Dev loss 60.000000', 'Train/Dev F1: 12.000000 34.000000', 'Train/Dev EM: 22.000000 88.000000')


In [215]:
tf.reset_default_graph()
d=tf.constant([[[3,2],[7,8],[1,1]],
               [[0,5],[1,8],[4,9]],
               [[6,3],[2,7],[9,5]]])

guess_start = []
for t in range(4):
    samples = tf.multinomial(tf.log([[10., 10.,20,50],[10,10,10,10],[20,20,20,20]]), 1,seed=10)
    guess_start.append(samples)


with tf.Session() as sess:
#     print(sess.run(d))
#     print(sess.run(d[:,:,0]))
    print(guess_start)
    print(sess.run(guess_start))
    ss = tf.stack(guess_start)
    print(ss)
    print(sess.run(ss))

[<tf.Tensor 'multinomial/Multinomial:0' shape=(3, 1) dtype=int64>, <tf.Tensor 'multinomial_1/Multinomial:0' shape=(3, 1) dtype=int64>, <tf.Tensor 'multinomial_2/Multinomial:0' shape=(3, 1) dtype=int64>, <tf.Tensor 'multinomial_3/Multinomial:0' shape=(3, 1) dtype=int64>]
[array([[2],
       [1],
       [0]]), array([[2],
       [1],
       [0]]), array([[2],
       [1],
       [0]]), array([[2],
       [1],
       [0]])]
Tensor("stack:0", shape=(4, 3, 1), dtype=int64)
[[[2]
  [2]
  [2]]

 [[2]
  [2]
  [2]]

 [[2]
  [2]
  [2]]

 [[2]
  [2]
  [2]]]


In [185]:
reward=[]
reward.append([2,3])
reward.append([4,6])
print(reward)
print(np.array(reward))

[[2, 3], [4, 6]]
[[2 3]
 [4 6]]


In [195]:
tf.reset_default_graph()
y = tf.placeholder(tf.int32, (None,), name='y1')
reward=[]
for i in range(4):
    reward.append(y)
with tf.Session() as sess:
    print((reward))
    print((tf.stack(reward)))

[<tf.Tensor 'y1:0' shape=(?,) dtype=int32>, <tf.Tensor 'y1:0' shape=(?,) dtype=int32>, <tf.Tensor 'y1:0' shape=(?,) dtype=int32>, <tf.Tensor 'y1:0' shape=(?,) dtype=int32>]
Tensor("stack:0", shape=(4, ?), dtype=int32)


In [205]:
tf.reset_default_graph()
d1=tf.constant([[[3,2,1,4],[7,8,9,2],[1,1,1,3]],
               [[0,0,0,5],[1,1,1,8],[1,1,1,9]]])
d2=tf.constant([[[13,2,1,4],[7,18,9,2],[1,1,31,3]],
               [[30,0,0,5],[61,1,1,8],[1,1,41,9]]])
ta = tf.TensorArray(dtype=tf.int32, size=2)
ta=ta.write(0, d1)
ta=ta.write(1, d2)
with tf.Session() as sess:
    print((ta))
    print(tf.shape(ta.concat()))
    print(sess.run(ta.concat()))

Tensor("Shape:0", shape=(3,), dtype=int32)
[[[ 3  2  1  4]
  [ 7  8  9  2]
  [ 1  1  1  3]]

 [[ 0  0  0  5]
  [ 1  1  1  8]
  [ 1  1  1  9]]

 [[13  2  1  4]
  [ 7 18  9  2]
  [ 1  1 31  3]]

 [[30  0  0  5]
  [61  1  1  8]
  [ 1  1 41  9]]]


In [207]:
tf.reset_default_graph()
first=tf.constant(np.array([[1,2],[3,4],[7,8]]))
print(first)
ss = tf.reshape(first,[-1])
print(ss)
with tf.Session() as sess:
    print(sess.run(first))
    print(sess.run(ss))

Tensor("Const:0", shape=(3, 2), dtype=int64)
Tensor("Reshape:0", shape=(6,), dtype=int64)
[[1 2]
 [3 4]
 [7 8]]
[1 2 3 4 7 8]


In [214]:
tf.reset_default_graph()
y = tf.constant([20,25,30,10,1,2,3,4,11,12,33,4])
with tf.Session() as sess:
    print(sess.run(tf.split(y, 3)))
    print(sess.run(tf.stack(tf.split(y, 3), axis=1)))
    print(sess.run(tf.expand_dims(y, axis=1)))

[array([20, 25, 30, 10], dtype=int32), array([1, 2, 3, 4], dtype=int32), array([11, 12, 33,  4], dtype=int32)]
[[20  1 11]
 [25  2 12]
 [30  3 33]
 [10  4  4]]
[[20]
 [25]
 [30]
 [10]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [11]
 [12]
 [33]
 [ 4]]


In [217]:
tf.reset_default_graph()
final_start_logits =tf.constant([[20,25,30,10,4],[1,2,3,4,5],[11,2,3,4,5]])
reward = tf.zeros(tf.shape(final_start_logits[0]), dtype=tf.float32)
with tf.Session() as sess:
    print(sess.run(reward))

[ 0.  0.  0.  0.  0.]


In [7]:
#Multi-class cross-entropy
#p and q are expected to be probability distributions over N classes. 
#In particular, N can be 2, as in the following example
p = tf.placeholder(tf.float32, shape=[None, 2])
logit_q = tf.placeholder(tf.float32, shape=[None, 2])
q = tf.nn.softmax(logit_q)

feed_dict = {
  p: [[0, 1],
      [1, 0],
      [1, 0]],
  logit_q: [[0.2, 0.8],
            [0.7, 0.3],
            [0.5, 0.5]]
}

prob1 = -tf.reduce_sum(p * tf.log(q), axis=1)
prob2 = tf.nn.softmax_cross_entropy_with_logits(labels=p, logits=logit_q)
with tf.Session() as sess:
    print(sess.run(prob1, feed_dict))  # [ 0.43748799  0.51301527  0.69314718]
    print(sess.run(prob2,feed_dict))  # [ 0.43748799  0.51301527  0.69314718]

[ 0.43748796  0.51301527  0.69314718]
[ 0.43748799  0.51301527  0.69314718]


In [9]:
#Binary cross-entropy
p = tf.placeholder(tf.float32, shape=[None, 5])
logit_q = tf.placeholder(tf.float32, shape=[None, 5])
q = tf.nn.sigmoid(logit_q)

feed_dict = {
  p: [[0, 0, 0, 1, 0],
      [1, 0, 0, 0, 0]],
  logit_q: [[0.2, 0.2, 0.1, 0.4, 0.1],
            [0.3, 0.3, 0.2, 0.1, 0.1]]
}

prob1 = -p * tf.log(q)
prob2 = p * -tf.log(q) + (1 - p) * -tf.log(1 - q)
prob3 = p * -tf.log(tf.sigmoid(logit_q)) + (1-p) * -tf.log(1-tf.sigmoid(logit_q))
prob4 = tf.nn.sigmoid_cross_entropy_with_logits(labels=p, logits=logit_q)
with tf.Session() as sess:
    print (sess.run(q, feed_dict))
#     print(sess.run(prob1, feed_dict))
#     print(sess.run(prob2,feed_dict))
#     print(sess.run(prob3, feed_dict))
#     print(sess.run(prob4,feed_dict))
     

[[ 0.54983395  0.54983395  0.52497917  0.59868765  0.52497917]
 [ 0.57444251  0.57444251  0.54983395  0.52497917  0.52497917]]


In [15]:
act_probs=tf.constant([[0.2,0.3,0.5],[0.4,0.3,0.3]])
entropy_1 = act_probs *(tf.clip_by_value(act_probs, 1e-10, 1.0))
entropy = -tf.reduce_sum(act_probs *
                         tf.log(tf.clip_by_value(act_probs, 1e-10, 1.0)), axis=1)
with tf.Session() as sess:
    print(sess.run(entropy_1))
    print(sess.run(entropy))

[[ 0.04        0.09        0.25      ]
 [ 0.16000001  0.09        0.09      ]]
[ 1.02965307  1.08890009]


In [17]:
graph = tf.get_default_graph()

var = tf.Variable(0)

for s in xrange(2):
    with tf.name_scope('myscope_%d' % s):
        op = var.assign_add(s + 1)

all_operations = [graph.get_operation_by_name('myscope_%d/AssignAdd' % s) for s in range(2)]
all_op = tf.group(*all_operations)

In [18]:
sess = tf.Session()
sess.run(tf.initialize_all_variables())
print sess.run(var)  # prints 0
sess.run(all_op)
print sess.run(var)  # prints 3

Instructions for updating:
Use `tf.global_variables_initializer` instead.


Instructions for updating:
Use `tf.global_variables_initializer` instead.


0
3


In [8]:
graph = tf.get_default_graph()
q = tf.FIFOQueue(3,'float')
init = q.enqueue_many(([0.,0.,0.,],))
x = q.dequeue()
y=x+1
q_inc = q.enqueue([y])
with tf.Session() as sess:
    init.run()
    q_inc.run()
    q_inc.run()
    q_inc.run()
    q_inc.run()
    print sess.run(x)
    print sess.run(y)
    print "mehdi"

1.0
2.0
mehdi


In [9]:
# create a dataset that counts from 0 to 99
graph = tf.get_default_graph()
input = tf.constant(list(range(100)))
input = tf.data.Dataset.from_tensor_slices(input)
input = input.make_one_shot_iterator().get_next()
with tf.Session() as sess:
    print sess.run(input)
    

AttributeError: 'module' object has no attribute 'data'

In [12]:
graph = tf.get_default_graph()
rewards = b=tf.constant([1,7,7,2])
reward_ph = tf.expand_dims(rewards, 1)
with tf.Session() as sess:
    print sess.run(rewards) 
    print sess.run(reward_ph)

[1 7 7 2]
[[1]
 [7]
 [7]
 [2]]


In [9]:
tf.reset_default_graph()
d1=tf.constant([[3,2,1,4],[7,8,9,2],[1,1,1,3],[0,0,0,5],[1,1,1,8],[1,1,1,9]])
with tf.Session() as sess:
    print((sess.run(d1)))
    print (sess.run(tf.argmax(d1, axis = -1)))
    print (sess.run(tf.one_hot(3,12)))

[[3 2 1 4]
 [7 8 9 2]
 [1 1 1 3]
 [0 0 0 5]
 [1 1 1 8]
 [1 1 1 9]]
[3 2 3 3 3 3]
[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]


In [20]:
tf.reset_default_graph()

a=tf.constant([[[[3,2,1],[7,8,9],[1,1,1]],[[3,2,1],[7,8,9],[1,1,1]],[[9,2,1],[7,8,9],[1,1,1]]],
               [[[0,0,0],[1,1,1],[1,1,1]],[[3,2,1],[7,8,9],[1,1,1]],[[5,2,1],[7,8,9],[1,1,1]]], 
               [[[2,2,2],[3,3,3],[1,1,1]],[[3,2,1],[7,8,9],[1,1,1]],[[13,2,1],[7,8,9],[1,1,1]]], 
               [[[4,4,4],[5,5,5],[1,1,1]],[[3,2,1],[7,8,9],[1,1,1]],[[4,2,1],[7,8,9],[1,1,1]]]])
print (a)
b=a[:, 0, ...]
print(b)
with tf.Session() as sess:
    print(sess.run(a))
    print("sssssss")
    print(sess.run(b))

Tensor("Const:0", shape=(4, 3, 3, 3), dtype=int32)
Tensor("strided_slice:0", shape=(4, 3, 3), dtype=int32)
[[[[ 3  2  1]
   [ 7  8  9]
   [ 1  1  1]]

  [[ 3  2  1]
   [ 7  8  9]
   [ 1  1  1]]

  [[ 9  2  1]
   [ 7  8  9]
   [ 1  1  1]]]


 [[[ 0  0  0]
   [ 1  1  1]
   [ 1  1  1]]

  [[ 3  2  1]
   [ 7  8  9]
   [ 1  1  1]]

  [[ 5  2  1]
   [ 7  8  9]
   [ 1  1  1]]]


 [[[ 2  2  2]
   [ 3  3  3]
   [ 1  1  1]]

  [[ 3  2  1]
   [ 7  8  9]
   [ 1  1  1]]

  [[13  2  1]
   [ 7  8  9]
   [ 1  1  1]]]


 [[[ 4  4  4]
   [ 5  5  5]
   [ 1  1  1]]

  [[ 3  2  1]
   [ 7  8  9]
   [ 1  1  1]]

  [[ 4  2  1]
   [ 7  8  9]
   [ 1  1  1]]]]
sssssss
[[[3 2 1]
  [7 8 9]
  [1 1 1]]

 [[0 0 0]
  [1 1 1]
  [1 1 1]]

 [[2 2 2]
  [3 3 3]
  [1 1 1]]

 [[4 4 4]
  [5 5 5]
  [1 1 1]]]


In [17]:
x = tf.constant([[1,2], [3,4], [5,6]], dtype =tf.float32)
mean, variance = tf.nn.moments(x, [0])
with tf.Session() as sess:
    m, v = sess.run([mean, variance])
    print(m)
    print(v)

[ 3.  4.]
[ 2.66666675  2.66666675]


In [34]:
tf.reset_default_graph()
prob = tf.constant([[0.1, 0.2, 0.7],[0.3, 0.3, 0.4]], dtype =tf.float32)
with tf.Session() as sess:
    temp= tf.squeeze(sess.run(tf.multinomial(prob,1)))
    print(temp)
    print(temp.shape)

Tensor("Squeeze:0", shape=(2,), dtype=int64)
(2,)


In [8]:
res = [0]
n=8
prices=[1,15,18,35,15,17,17,20]
def helper(curN, prices, curVal, res):
    #print(curN,res,curVal)
    if curN==0:
        res[0]=max(curVal, res[0])
        return
    for i in range(1,curN+1):
        helper(curN-i, prices, curVal+prices[i-1],res)
helper(n, prices,0,res)
print (res[0])

70


In [16]:
tf.reset_default_graph()
#x = [0., 1., 2., 3., 4., 5., 6., 7.]
#y = tf.reshape(x, [2, 2, 2])
#unstack_axis0 = tf.unstack(y, axis=0)
x = tf.constant([[1, 4], [8,9]])
y = tf.constant([[2, 5],[12,19]])
#z = tf.constant([[3, 6],[2,7]])
aa = tf.stack([x,y])
bb = tf.unstack(aa)
ss = tf.one_hot(3, 7, 1.0, 0.0)
with tf.Session() as sess:
    print (sess.run(aa))
    print (sess.run(bb))
    print (sess.run(ss))
    print(sess.run(tf.reduce_sum(x)))
    #print(sess.run(unstack_axis0))


[[[ 1  4]
  [ 8  9]]

 [[ 2  5]
  [12 19]]]
[array([[1, 4],
       [8, 9]], dtype=int32), array([[ 2,  5],
       [12, 19]], dtype=int32)]
[ 0.  0.  0.  1.  0.  0.  0.]
22


In [29]:
def body(i, x):
    a = tf.random_uniform(shape=[2, 2], dtype=tf.int32, maxval=100)
    b = tf.constant(np.array([[1, 2], [3, 4]]), dtype=tf.int32)
    c = a + b
    return i+1, tf.nn.relu(x + c)

def condition(i, x):
    return tf.reduce_sum(i) < 10
    #return lambda i, _1: i < 5
    
x = tf.Variable(tf.constant(0, shape=[2, 2]))
i = tf.constant(0, dtype=tf.int32)

with tf.Session():
    tf.global_variables_initializer().run()
    _, result = tf.while_loop(condition, body, [i,x])
    print(result.eval())

[[666 497]
 [730 588]]


In [3]:
tf.reset_default_graph()
x = tf.identity(0)
print(x)
with tf.Session() as sess:
    print (sess.run(x))

Tensor("Identity:0", shape=(), dtype=int32)
0


In [5]:
tf.reset_default_graph()
warmup=0.002
x = 0.003
s = tf.cast(x <= warmup, tf.float32)
with tf.Session() as sess:
    print(sess.run(s))

0.0
